// Code generated by "stringer -type=GatewayOpcode -output=gateway_string.go"; DO NOT EDIT.

package flo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GatewayOpDispatch-0]
	_ = x[GatewayOpHeartbeat-1]
	_ = x[GatewayOpIdentify-2]
	_ = x[GatewayOpPresenceUpdate-3]
	_ = x[GatewayOpVoiceStateUpdate-4]
	_ = x[GatewayOpResume-6]
	_ = x[GatewayOpReconnect-7]
	_ = x[GatewayOpRequestGuildMembers-8]
	_ = x[GatewayOpInvalidSession-9]
	_ = x[GatewayOpHello-10]
	_ = x[GatewayOpHeartbeatACK-11]
}

const (
	_GatewayOpcode_name_0 = "GatewayOpDispatchGatewayOpHeartbeatGatewayOpIdentifyGatewayOpPresenceUpdateGatewayOpVoiceStateUpdate"
	_GatewayOpcode_name_1 = "GatewayOpResumeGatewayOpReconnectGatewayOpRequestGuildMembersGatewayOpInvalidSessionGatewayOpHelloGatewayOpHeartbeatACK"
)

var (
	_GatewayOpcode_index_0 = [...]uint8{0, 17, 35, 52, 75, 100}
	_GatewayOpcode_index_1 = [...]uint8{0, 15, 33, 61, 84, 98, 119}
)

func (i GatewayOpcode) String() string {
	switch {
	case i <= 4:
		return _GatewayOpcode_name_0[_GatewayOpcode_index_0[i]:_GatewayOpcode_index_0[i+1]]
	case 6 <= i && i <= 11:
		i -= 6
		return _GatewayOpcode_name_1[_GatewayOpcode_index_1[i]:_GatewayOpcode_index_1[i+1]]
	default:
		return "GatewayOpcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
