// Code generated by "stringer -type=UserNotifSettings -output=model_user_string.go"; DO NOT EDIT.

package flo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UserNotifSettingsAllMessages-0]
	_ = x[UserNotifSettingsOnlyMentions-1]
	_ = x[UserNotifSettingsNoMessages-2]
	_ = x[UserNotifSettingsInherit-3]
}

const _UserNotifSettings_name = "UserNotifSettingsAllMessagesUserNotifSettingsOnlyMentionsUserNotifSettingsNoMessagesUserNotifSettingsInherit"

var _UserNotifSettings_index = [...]uint8{0, 28, 57, 84, 108}

func (i UserNotifSettings) String() string {
	if i >= UserNotifSettings(len(_UserNotifSettings_index)-1) {
		return "UserNotifSettings(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserNotifSettings_name[_UserNotifSettings_index[i]:_UserNotifSettings_index[i+1]]
}
