// Code generated by "stringer -type=ChannelType,ChannelPermOverwriteType -output=model_channel_string.go"; DO NOT EDIT.

package flo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChannelTypeGuildText-0]
	_ = x[ChannelTypeDM-1]
	_ = x[ChannelTypeGuildVoice-2]
	_ = x[ChannelTypeGroupDM-3]
	_ = x[ChannelTypeGuildCategory-4]
	_ = x[ChannelTypeGuildLink-998]
	_ = x[ChannelTypeDMPersonalNotes-999]
}

const (
	_ChannelType_name_0 = "ChannelTypeGuildTextChannelTypeDMChannelTypeGuildVoiceChannelTypeGroupDMChannelTypeGuildCategory"
	_ChannelType_name_1 = "ChannelTypeGuildLinkChannelTypeDMPersonalNotes"
)

var (
	_ChannelType_index_0 = [...]uint8{0, 20, 33, 54, 72, 96}
	_ChannelType_index_1 = [...]uint8{0, 20, 46}
)

func (i ChannelType) String() string {
	switch {
	case i <= 4:
		return _ChannelType_name_0[_ChannelType_index_0[i]:_ChannelType_index_0[i+1]]
	case 998 <= i && i <= 999:
		i -= 998
		return _ChannelType_name_1[_ChannelType_index_1[i]:_ChannelType_index_1[i+1]]
	default:
		return "ChannelType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChannelPermOverwriteTypeRole-0]
	_ = x[ChannelPermOverwriteTypeMember-1]
}

const _ChannelPermOverwriteType_name = "ChannelPermOverwriteTypeRoleChannelPermOverwriteTypeMember"

var _ChannelPermOverwriteType_index = [...]uint8{0, 28, 58}

func (i ChannelPermOverwriteType) String() string {
	if i >= ChannelPermOverwriteType(len(_ChannelPermOverwriteType_index)-1) {
		return "ChannelPermOverwriteType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChannelPermOverwriteType_name[_ChannelPermOverwriteType_index[i]:_ChannelPermOverwriteType_index[i+1]]
}
