// Code generated by "stringer -type=MessageType,MessageReferenceType -output=model_message_string.go"; DO NOT EDIT.

package flo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageTypeDefault-0]
	_ = x[MessageTypeRecipientAdd-1]
	_ = x[MessageTypeRecipientRemove-2]
	_ = x[MessageTypeCall-3]
	_ = x[MessageTypeChannelNameChange-4]
	_ = x[MessageTypeChannelIconChange-5]
	_ = x[MessageTypeChannelPinnedMessage-6]
	_ = x[MessageTypeUserJoin-7]
	_ = x[MessageTypeReply-19]
}

const (
	_MessageType_name_0 = "MessageTypeDefaultMessageTypeRecipientAddMessageTypeRecipientRemoveMessageTypeCallMessageTypeChannelNameChangeMessageTypeChannelIconChangeMessageTypeChannelPinnedMessageMessageTypeUserJoin"
	_MessageType_name_1 = "MessageTypeReply"
)

var (
	_MessageType_index_0 = [...]uint8{0, 18, 41, 67, 82, 110, 138, 169, 188}
)

func (i MessageType) String() string {
	switch {
	case i <= 7:
		return _MessageType_name_0[_MessageType_index_0[i]:_MessageType_index_0[i+1]]
	case i == 19:
		return _MessageType_name_1
	default:
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageReferenceTypeDefault-0]
	_ = x[MessageReferenceTypeForward-1]
}

const _MessageReferenceType_name = "MessageReferenceTypeDefaultMessageReferenceTypeForward"

var _MessageReferenceType_index = [...]uint8{0, 27, 54}

func (i MessageReferenceType) String() string {
	if i >= MessageReferenceType(len(_MessageReferenceType_index)-1) {
		return "MessageReferenceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageReferenceType_name[_MessageReferenceType_index[i]:_MessageReferenceType_index[i+1]]
}
