// Code generated by "stringer -type=GuildSplashCardAlignment,GuildVerifLevel,GuildMFALevel,GuildNSFWLevel,GuildExplicitContentFilter -output=model_guild_string.go"; DO NOT EDIT.

package flo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GuildSplashCardAlignCenter-0]
	_ = x[GuildSplashCardAlignLeft-1]
	_ = x[GuildSplashCardAlignRight-2]
}

const _GuildSplashCardAlignment_name = "GuildSplashCardAlignCenterGuildSplashCardAlignLeftGuildSplashCardAlignRight"

var _GuildSplashCardAlignment_index = [...]uint8{0, 26, 50, 75}

func (i GuildSplashCardAlignment) String() string {
	if i >= GuildSplashCardAlignment(len(_GuildSplashCardAlignment_index)-1) {
		return "GuildSplashCardAlignment(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GuildSplashCardAlignment_name[_GuildSplashCardAlignment_index[i]:_GuildSplashCardAlignment_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GuildVerifLevelNone-0]
	_ = x[GuildVerifLevelLow-1]
	_ = x[GuildVerifLevelMedium-2]
	_ = x[GuildVerifLevelHigh-3]
	_ = x[GuildVerifLevelVeryHeigh-4]
}

const _GuildVerifLevel_name = "GuildVerifLevelNoneGuildVerifLevelLowGuildVerifLevelMediumGuildVerifLevelHighGuildVerifLevelVeryHeigh"

var _GuildVerifLevel_index = [...]uint8{0, 19, 37, 58, 77, 101}

func (i GuildVerifLevel) String() string {
	if i >= GuildVerifLevel(len(_GuildVerifLevel_index)-1) {
		return "GuildVerifLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GuildVerifLevel_name[_GuildVerifLevel_index[i]:_GuildVerifLevel_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GuildMFALevelNone-0]
	_ = x[GuildMFALevelElevated-1]
}

const _GuildMFALevel_name = "GuildMFALevelNoneGuildMFALevelElevated"

var _GuildMFALevel_index = [...]uint8{0, 17, 38}

func (i GuildMFALevel) String() string {
	if i >= GuildMFALevel(len(_GuildMFALevel_index)-1) {
		return "GuildMFALevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GuildMFALevel_name[_GuildMFALevel_index[i]:_GuildMFALevel_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GuildNSFWLevelDefault-0]
	_ = x[GuildNSFWLevelExplicit-1]
	_ = x[GuildNSFWLevelSafe-2]
	_ = x[GuildNSFWLevelAgeRestricted-3]
}

const _GuildNSFWLevel_name = "GuildNSFWLevelDefaultGuildNSFWLevelExplicitGuildNSFWLevelSafeGuildNSFWLevelAgeRestricted"

var _GuildNSFWLevel_index = [...]uint8{0, 21, 43, 61, 88}

func (i GuildNSFWLevel) String() string {
	if i >= GuildNSFWLevel(len(_GuildNSFWLevel_index)-1) {
		return "GuildNSFWLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GuildNSFWLevel_name[_GuildNSFWLevel_index[i]:_GuildNSFWLevel_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GuildExplicitContentFilterDisabled-0]
	_ = x[GuildExplicitContentFilterMembersWithoutRoles-1]
	_ = x[GuildExplicitContentFilterAllMembers-2]
}

const _GuildExplicitContentFilter_name = "GuildExplicitContentFilterDisabledGuildExplicitContentFilterMembersWithoutRolesGuildExplicitContentFilterAllMembers"

var _GuildExplicitContentFilter_index = [...]uint8{0, 34, 79, 115}

func (i GuildExplicitContentFilter) String() string {
	if i >= GuildExplicitContentFilter(len(_GuildExplicitContentFilter_index)-1) {
		return "GuildExplicitContentFilter(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GuildExplicitContentFilter_name[_GuildExplicitContentFilter_index[i]:_GuildExplicitContentFilter_index[i+1]]
}
